### ISSUE TITLE
看了半天实在不懂怎么图片上传并返回图片路径

### ISSUE THREAD

**Issue by gg22mm** [swlib/saber#107]
看了半天实在不懂怎么图片上传并返回图片路径？  软件可能很好，说明写得太low了

//图片上传
	public function upload(){
		$file=$this->request->file('file');	
		print_r($file);
		print_r( $file->getRealPath() );//获取上传的文件路径
		
		$file2 = [
			'path' =>$file->getRealPath(),           //返回的是 /tmp/swoole.upfile.NxiaL3 二进制文字，这样怎么弄? 
			'name' => 'white.jpg',
			//'type' => ContentType::$Map['png'],
			//'offset' => null, //re-upload from break
			//'size' => null //upload a part of the file
		];
		
		echo $aa= SaberGM::post('http://httpbin.org/post', null, [
				'files' => [					
					'image2' => $file2,					
				]
			]
		);
		
		
	}

返回如下：

/tmp/swoole.upfile.NxiaL3HTTP/1.1 200 OK
Date: Tue, 08 Sep 2020 15:18:38 GMT
Content-Type: application/json
Content-Length: 35639
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {},
  "data": "",
  "files": {
    "image2": "data:white.jpg;base64,/9j/2wBDAAsJCgsKEQ0XFQsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQsODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAStAsQDASIAAhEBAxEB/8QAHAAAAwEBAQEBAQAAAAAAAAAAAQIDAAQFBgcI/8QAMRABAQEBAAMAAgEDAwMDBQADAAECEQMSIQQxQQUTUQYiYRRCcTJDgRUjUlORRFSh/8QAGQEBA

**Comment by sy-records** [comment]
只不过提供了三种方式，看不懂可以用最简单的`string`，传文件路径即可。

你的已经上传成功了，`httpbin.org/post`上传文件会返回`base64`，也就是你看到的这一大堆
```
"files": {
"image2": "data:white.jpg;base64,/9j/2wBDAAsJCgsKEQ0XFQsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlN
```

`/tmp/swoole.upfile.NxiaL3`这就是swoole的http server上传文件时的临时文件路径，按照自己的需求移动到指定目录就是了

https://wiki.swoole.com/#/http_server?id=files
