### ISSUE TITLE
请求一直乱码

### ISSUE THREAD

**Issue by scfff** [swlib/saber#108]
第一次使用，不知道什么原因，一直乱码。

       //乱码
        $uri = "https://wenda.swoole.com";
        $content = (string)SaberGM::get($uri)->getBody();
        echo $content;

        //正常
        $cli = new \Swoole\Coroutine\Http\Client('wenda.swoole.com', 443,true);
        $cli->get('/');
        echo $cli->body;
        $cli->close();

**Comment by sy-records** [comment]
我测试正常

**Comment by scfff** [comment]
我的配置环境是 wls2 ubunut20 PHP 7.4.3  用 swoole pecl 和源码编译 都会有这个问题。

**Comment by scfff** [comment]
这样的乱码
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.3.7
Cache-Control: no-cache, private
Date: Wed, 16 Sep 2020 11:42:05 GMT
Set-Cookie: swoole_session=eyJpdiI6ImNoMnVZTVk4dlJFTk54RnNMNU1jM3c9PSIsInZhbHVlIjoiVklPUThYWmJROHNFbVZcL2tocnVXTDNVQnZsNlZCeTVncFdaVytWSlFGQnpLWVk0VG1xM
mpwWWlGeUlzZW9KSlUiLCJtYWMiOiIyOTE1ZmQ1NDNhOGYzYTU2YmI1NmQ2MjEyNGM2YWY3ZTc4MmRkMDA2Y2MzZjg5NGIxNTQzMDVlMjJkOTZiMjViIn0%3D; expires=Fri, 18-Sep-2020 11:4
2:05 GMT; Max-Age=172800; path=/; httponly
Content-Encoding: gzip

╚]ysF?Cg-y)ČxwI\nmMM@╗$au8*9I'd8hfb9w~H
@.'^w׍&^5WQ٪&╔VZ,ܑE)DEDT()[UFc(AoR,UuU^dq#$ z9Ine&Vش"TuÊY═f*OJR║r)b)*║Q'S$0c\vS܌nH&IxO��Y|2X͂T-E׸i╔?^<Gl╝i,~`?b_a[SwO5l<O1ޡ<sH^?B|
ue˂V(B╝TEBeC.NbZ   sJR     "d3%=^J1dd,CjyIfbV@
HcabeZXEL#9╝I1║LYxEpѶT,24<!Y
                            'q:      ╔%cn`DUZIP╝4=ə,.╔Z     fSVG$
g(U mFOGH]CWbad5MG{)zY`5I,^0F "��`*'L:%
╔O&?#╗:hh(qYVJe+       _AT6
c_╔dC0DI(j}Z6>3ʊ$ɚ)R
Cɼ   "twOkIF{f8ڟJO%ۤ^Q:L]U4a.MGVIL't6ddhf<Ȑ䤃@' A
                                                   :Q\2he,╝9ZZ-P8*΍91ۉ_9pyYzbRe/n{&~SUu║ Ohj&ugʊEJ╗9P*4=/║R0'h4╚0)cPr╚&N1ˊ,)"
B,ȲDMBq1бG╗Y+z^Q尢rJ*m_|0H()`q
7)͢HP$@

       v2i2F[ v3X`F   xirv0NƎ+7H灷tC╔═༢:`ɘ*&~XvwAgМZb7pQ$#i<^b3؁Lo╗jZ$D))$<2B'Wɴ║`DBW╝!Y~.)XLq8b@MƠbՔm=<yC
                                                                                                          T
                                                                                                           "YBˆ=.,E
P@2I@I╝ˢ{,H6([VO$ffft9[ƘHJUk҈    U+
)ڶHR|%_?[_%*5;e
^h[~l
     &/[',uQ$|V╗╝2'[eI&Zr,Wty
                             * SV;uڰ#
                                     5`6LMo691
cTC\8═
      G.ő╚!gX`Nܭs~M%bomA║ja╗╝lk╝n═[>νAM9`DVv&7�(r
                                                  2=VM0╚&&d^║SlLm+<C;2MK/g.nS٘R%IJ*Vʆ8Y     fr}qG?v7,ujuyG     ZS/Z3!C0��
Mԫ
or╔(
:C G
    @aBfY╝M0+j       iT╚x5sU(R=@.a"╔vU║~ʎ╔{9#h╝7-S)10abɁ║'#Q}zqŎ"ΨD;+UǠ̵1i(@~*ֶ.sgV}[f6KP]s6okat"~}L7L=~ ~S0KѪ5
                                                                                                               lzکW:\h~GBZQa═Ť\UXtS
]8╝lvĤF&gX`Dx$ݔ╔e>CVPFQR}L&\Dׂd]O⊤ '&
˟Gqg+ߡSc>|ΘrTi6׸X^UF4q40P_&VӺb!g̟iY╝[^l9tnySEO*<c%^_"Sv$^`uׁBSi?╔Sݱ9b2)╗
                                                                         Nl
                                                                           "]'^X
                                                                                |̴Df}֒MUci═TdKA7f║lzZhkhsX$ (ηis>Sg═JeL3_憐A!V
J╗9!^q-no��iT4^╔Xbz+Y
                     0=j:
═5_V`We+Io,_u=wY?]+8aG_xzuIh{>Z}       1˽
                                         ╝G═\?'`
Kɭ4,yrwVv"բϟ}zھx}uRU

**Comment by sy-records** [comment]
上linux可以复现吗？

**Comment by ta244100** [comment]
gzip就是那种乱码，你看看是不是用程序的请求需要解码gzip

**Comment by scfff** [comment]
> 上linux可以复现吗？

linux跑正常，
这个环境下GuzzleHttp试了也有这个问题，=_=!

**Comment by sy-records** [comment]
那我先关掉了... 没用过wsl 你得自己研究下
