### ISSUE TITLE
hello,源码的功能注释可以加上吗？用起来好些时候demo并不能有完全的作用

### ISSUE THREAD

**Issue by lishuncoder** [swlib/saber#110]
比如 getParsedJsonArray 这个函数，我愣是看文档和 SaberTest 去猜出来的，虽然指明是解析json，源码是否可以加上一些简单的功能说明呢。。。。

**Comment by sy-records** [comment]
README里找一下，跑一下示例应该就知道啥意思了吧。。https://github.com/swlib/saber#%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90
