### ISSUE TITLE
开启use_pool为true时，第二次请求当body为空时，body未重置，导致请求把上次请求的body带到下次请求的body

### ISSUE THREAD

**Issue by jeanslin** [swlib/saber#115]
操作步骤：
1、设置use_pool为true
2、第一次发送POST请求，并带上body
3、第二次发送GET请求，没有body

结果：第二次GET请求的Body为第一次POST请求的body，实际上第二次GET请求并为带上任何Body参数

定位错误文件路径：swlib/saber/src/Request.php:627
`
         /** 设置请求主体 */
        $body = (string) ($this->getBody() ?? '');
        if ($body !== '') {
            $this->client->setData($body);
        }
`

**Comment by sy-records** [comment]
这样吗？

```php
use Swlib\Saber;

\Co\run(function () {
    $httpbin = Saber::create([
        'base_uri' => 'http://httpbin.org/',
        'use_pool' => true
    ]);
    $res = $httpbin->post('/post', ['foo' => 'bar']);
    var_dump((string)$res->body);
    $res = $httpbin->get('/get');
    var_dump((string)$res->body);
});
```

**Comment by jeanslin** [comment]
> 这样吗？
> 
> ```
> use Swlib\Saber;
> 
> \Co\run(function () {
>     $httpbin = Saber::create([
>         'base_uri' => 'http://httpbin.org/',
>         'use_pool' => true
>     ]);
>     $res = $httpbin->post('/post', ['foo' => 'bar']);
>     var_dump((string)$res->body);
>     $res = $httpbin->get('/get');
>     var_dump((string)$res->body);
> });
> ```

嗯嗯，类似这样的结构哈，这边的代码是这样的，如果上次请求为post，那么下次get请求body为空，则会把上次post请求的body也带过去
```
$client = Saber::create([
            'base_uri' => $apiUrl,
            'use_pool' => true,
        ]);

$resp = $client->request([
    'method'  => $method,
    'uri'     => $dstReqUri,
    'timeout' => 60.000,
    'headers' => $headers,
    'cookies' => false,
    'body'    => $bodyContent,
]);
```

**Comment by sy-records** [comment]
给个完整的复现代码..

**Comment by lovexiaowei** [comment]
客户端是这要写的
![image](https://user-images.githubusercontent.com/18624879/106155010-2c016680-61bb-11eb-8398-6ba00de32328.png)
服务端是这样弄的
![image](https://user-images.githubusercontent.com/18624879/106155075-3b80af80-61bb-11eb-974d-400bdf310cb7.png)
打印的结果 是这样，
![image](https://user-images.githubusercontent.com/18624879/106155103-43405400-61bb-11eb-85cb-f706d552d917.png)
这个是不是就是没有清空？还是我使用错了

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/106219338-21bf8680-6214-11eb-8f27-abde12906d84.png)

没复现。。

**Comment by jeanslin** [comment]
> ![image](https://user-images.githubusercontent.com/33931153/106219338-21bf8680-6214-11eb-8f27-abde12906d84.png)
> 
> 没复现。。

同一个进程调用两次saber::create可以复现

客户端代码为：
![image](https://user-images.githubusercontent.com/10190115/106221937-7c0f1600-6219-11eb-9b8d-4c37bc04e900.png)

服务端代码：
![image](https://user-images.githubusercontent.com/10190115/106222039-a95bc400-6219-11eb-9ac3-b233e92c536c.png)

服务端打印结果：
![image](https://user-images.githubusercontent.com/10190115/106222052-b4165900-6219-11eb-8b91-ea3b102c0bc2.png)


个人分析原因仅供参考：当开启use_pool时，Saber::create在同一进程里面会缓存saber的请求对象,加上以下代码逻辑导致get请求body未被重置
定位错误代码：swlib/saber/src/Request.php:627
![image](https://user-images.githubusercontent.com/10190115/106222155-ee7ff600-6219-11eb-91e7-9024c6e6353a.png)
此处在body不为空才会重置，如果是get未设置body时，这里直接跳过，body还是上次post请求的body

**Comment by sy-records** [comment]
@tomorrowsky @lovexiaowei 试下 #116 的代码
