### ISSUE TITLE
请问爬虫多IP爬取设置在什么地方

### ISSUE THREAD

**Issue by a1051575078** [swlib/saber#118]
我是一台站群服务器，当我进行get测试后，发现访问的都是同一条IP，我这台服务器本身是有200多个IP。经过swoole_get_local_ip()验证，也的确有200多个IP。如何才能使saber插件像curl 使用这个配置就可以指定IP进行访问呢？谢谢赐教curl_setopt($ch,CURLOPT_INTERFACE,$_SERVER['SERVER_ADDR']);

**Comment by a1051575078** [comment]
我操。谢谢大牛！。我已经好了！。可以留下支付宝吗，我眯着眼睛打，打多打少讲究个缘。
if (isset($options['bind_address'])) {
$request->withBindAddress(Saber.php 引用方法的时候你少了参数：$options['bind_address']);
}

**Comment by sy-records** [comment]
![image](https://user-images.githubusercontent.com/33931153/110401017-bdfe6800-80b3-11eb-96d8-eec084660bd3.png)
