### ISSUE TITLE
http请求输出乱码 

### ISSUE THREAD

**Issue by Niexiawei** [swlib/saber#121]
![image](https://user-images.githubusercontent.com/29922984/111899669-0846f800-8a69-11eb-94fa-9c1d2bb2b825.png)
### 请求参数 

![image](https://user-images.githubusercontent.com/29922984/111899679-15fc7d80-8a69-11eb-8d25-e63e643df757.png)
### 返回结果

系统是 docker 的debian 镜像  docker alpine 不会出现这个问题  是缺少了什么库吗

**Comment by Niexiawei** [comment]
![image](https://user-images.githubusercontent.com/29922984/111910091-f120fe00-8a9a-11eb-8b0a-e7605c6b4fac.png)

php  --ri swoole 信息

**Comment by Niexiawei** [comment]
破案了 需要 安装 zlib 

Debian 下执行 下面两个就行

- apt install zlib1g
- apt install zlib1g.dev
 

#### 编译时候出现这个 会有问题吗 编译虽然编译通过了

![image](https://user-images.githubusercontent.com/29922984/111910905-3430a080-8a9e-11eb-9658-8146e4f458b0.png)

**Comment by sy-records** [comment]
see https://github.com/swoole/swoole-src/issues/4095
