### ISSUE TITLE
批量下载图片的时候... terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by shuyabin** [swlib/saber#13]
正在下载图片http://xxxxx/school/images/10~12/2_01.jpg
正在下载图片http://fxxxx/school/images/10~12/2_02.jpg
正在下载图片http://xxxx/school/images/10~12/2_03.jpg
正在下载图片http://fxxxxschool/images/10~12/2_04.jpg
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

![image](https://user-images.githubusercontent.com/14884581/46427010-c62f7c00-c772-11e8-9207-508b2548a9ca.png)

**Comment by twose** [comment]
设备信息贴一下, 是不是爆内存了
没看明白你这个写法, 用`go`开子协程的话是会多协程并发的, go函数是立即返回的, 也就是说刚发起请求代码就会继续往下执行, 而不会等待下载完成.

**Comment by shuyabin** [comment]
是立即返回的…等于我就是异步下载图片，然后下载。下一个文章的图片…后面我换成同步的请求就正常…就是里面有异常的图片地址…然后就会这样… 8g内存。内存使用正常…

**Comment by shuyabin** [comment]
是立即返回的…等于我就是异步下载图片，然后下载。下一个文章的图片…后面我换成同步的请求就正常…就是里面有异常的图片地址…然后就会这样… 8g内存。内存使用正常…

**Comment by shuyabin** [comment]
是立即返回的…等于我就是异步下载图片，然后下载。下一个文章的图片…后面我换成同步的请求就正常…就是里面有异常的图片地址…然后就会这样… 8g内存。内存使用正常…

**Comment by shuyabin** [comment]
是立即返回的…等于我就是异步下载图片，然后下载。下一个文章的图片…后面我换成同步的请求就正常…就是里面有异常的图片地址…然后就会这样… 8g内存。内存使用正常…

**Comment by shuyabin** [comment]
是立即返回的…等于我就是异步下载图片，然后下载。下一个文章的图片…后面我换成同步的请求就正常…就是里面有异常的图片地址…然后就会这样… 8g内存。内存使用正常…

**Comment by twose** [comment]
@shuyabin 你这样描述不太好定位问题, 你可以给我们邮箱发一份可以直接运行的代码复现这个问题.
team@swoole.com

**Comment by twose** [comment]
@shuyabin 你可以尝试更新swoole版本看看是否正常
