### ISSUE TITLE
Connect timeout! the server is not listening on the port or the network is missing!

### ISSUE THREAD

**Issue by hjw1799** [swlib/saber#137]
SaberGM::post(
            $url, $params, [
                'headers' => $header ? $header : '',
                'timeout' => 0,
            ]
        );
正常的http请求也出现了这种，但是偶现，请问可以怎么处理

**Comment by hjw1799** [comment]
@twose

**Comment by sy-records** [comment]
timeout 调大点...

**Comment by hjw1799** [comment]
timeout试过调整为5,10,60，都有出现这种情况

**Comment by hjw1799** [comment]
> timeout 调大点...

timeout试过调整为5,10,60，都有出现这种情况

**Comment by sy-records** [comment]
你网络问题，可以使用swoole原生的http client加上timeout进行测试下

**Comment by sy-records** [comment]
你网络问题，可以使用swoole原生的http client加上timeout进行测试下
