### ISSUE TITLE
SaberGM::download中文名文件下载失败

### ISSUE THREAD

**Issue by heweitykc** [swlib/saber#144]
"name": "swlib/saber",
"version": "v1.0.18",

    $fileurl = "https://3.palmmob.com/testres/渐变色2.png";
    $dstpath = "/tmp/test.jpg";
    $response = Swlib\SaberGM::download($fileurl,$dstpath);

返回：
Uncaught Swlib\Http\Exception\ClientException: HTTP 400 Bad Request: Client side error, please check your configurations and permissions!

**Comment by sy-records** [comment]
低版本PHP需要转义下中文部分内容
