### ISSUE TITLE
获取请求内容乱码

### ISSUE THREAD

**Issue by ucdo** [swlib/saber#147]
……
$url = "https://apis.map.qq.com/ws/geocoder/v1/?location={$lat},{$lng}&key={$key}&get_poi={$get_poi}";
$response = SaberGM::get($url);
$response->getBoay()->getContents();乱码

PHP 8.1.2 (cli) 

[PHP Modules]

> bcmath
> calendar
> Core
> ctype
> curl
> date
> dom
> exif
> FFI
> fileinfo
> filter
> ftp
> gd
> gettext
> hash
> iconv
> igbinary
> intl
> json
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> xlswriter
> xml
> xmlreader
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib

swoole
> 
> Swoole => enabled
> Author => Swoole Team <team@swoole.com>
> Version => 4.8.9
> Built => Jun  9 2022 09:54:58
> coroutine => enabled with boost asm context
> epoll => enabled
> eventfd => enabled
> signalfd => enabled
> cpu_affinity => enabled
> spinlock => enabled
> rwlock => enabled
> openssl => OpenSSL 3.0.2 15 Mar 2022
> dtls => enabled
> http2 => enabled
> json => enabled
> mutex_timedlock => enabled
> pthread_barrier => enabled
> futex => enabled
> async_redis => enabled
> 
> Directive => Local Value => Master Value
> swoole.enable_coroutine => On => On
> swoole.enable_library => On => On
> swoole.enable_preemptive_scheduler => Off => Off
> swoole.display_errors => On => On
> swoole.use_shortname => Off => Off
> swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by zhaockorg** [comment]
无语。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "swlib/saber"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 上午10:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[swlib/saber] 获取请求内容乱码 (Issue #147)





 
……
 $url = "https://apis.map.qq.com/ws/geocoder/v1/?location={$lat},{$lng}&amp;key={$key}&amp;get_poi={$get_poi}";
 $response = SaberGM::get($url);
 $response-&gt;getBoay()-&gt;getContents();乱码
 
PHP 8.1.2 (cli)
 
[PHP Modules]
  
bcmath
 calendar
 Core
 ctype
 curl
 date
 dom
 exif
 FFI
 fileinfo
 filter
 ftp
 gd
 gettext
 hash
 iconv
 igbinary
 intl
 json
 libxml
 mbstring
 mysqli
 mysqlnd
 openssl
 pcntl
 pcre
 PDO
 xlswriter
 xml
 xmlreader
 xmlwriter
 xsl
 Zend OPcache
 zip
 zlib
  
swoole
  
Swoole =&gt; enabled
 Author =&gt; Swoole Team ***@***.***
 Version =&gt; 4.8.9
 Built =&gt; Jun  9 2022 09:54:58
 coroutine =&gt; enabled with boost asm context
 epoll =&gt; enabled
 eventfd =&gt; enabled
 signalfd =&gt; enabled
 cpu_affinity =&gt; enabled
 spinlock =&gt; enabled
 rwlock =&gt; enabled
 openssl =&gt; OpenSSL 3.0.2 15 Mar 2022
 dtls =&gt; enabled
 http2 =&gt; enabled
 json =&gt; enabled
 mutex_timedlock =&gt; enabled
 pthread_barrier =&gt; enabled
 futex =&gt; enabled
 async_redis =&gt; enabled
 
Directive =&gt; Local Value =&gt; Master Value
 swoole.enable_coroutine =&gt; On =&gt; On
 swoole.enable_library =&gt; On =&gt; On
 swoole.enable_preemptive_scheduler =&gt; Off =&gt; Off
 swoole.display_errors =&gt; On =&gt; On
 swoole.use_shortname =&gt; Off =&gt; Off
 swoole.unixsock_buffer_size =&gt; 8388608 =&gt; 8388608

**Comment by ucdo** [comment]
解决了，卸载之后只安装了swoole4.10，然后只开启了openssl扩展，就好了，不知道原因，但是能用。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月29日 10:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [swlib/saber] 获取请求内容乱码 (Issue #147) |

无语。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "swlib/saber" ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 上午10:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[swlib/saber] 获取请求内容乱码 (Issue #147)






……
$url = "https://apis.map.qq.com/ws/geocoder/v1/?location={$lat},{$lng}&amp;key={$key}&amp;get_poi={$get_poi}";
$response = SaberGM::get($url);
$response-&gt;getBoay()-&gt;getContents();乱码

PHP 8.1.2 (cli)

[PHP Modules]

bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
xlswriter
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

swoole

Swoole =&gt; enabled
Author =&gt; Swoole Team ***@***.***
Version =&gt; 4.8.9
Built =&gt; Jun 9 2022 09:54:58
coroutine =&gt; enabled with boost asm context
epoll =&gt; enabled
eventfd =&gt; enabled
signalfd =&gt; enabled
cpu_affinity =&gt; enabled
spinlock =&gt; enabled
rwlock =&gt; enabled
openssl =&gt; OpenSSL 3.0.2 15 Mar 2022
dtls =&gt; enabled
http2 =&gt; enabled
json =&gt; enabled
mutex_timedlock =&gt; enabled
pthread_barrier =&gt; enabled
futex =&gt; enabled
async_redis =&gt; enabled

Directive =&gt; Local Value =&gt; Master Value
swoole.enable_coroutine =&gt; On =&gt; On
swoole.enable_library =&gt; On =&gt; On
swoole.enable_preemptive_scheduler =&gt; Off =&gt; Off
swoole.display_errors =&gt; On =&gt; On
swoole.use_shortname =&gt; Off =&gt; Off
swoole.unixsock_buffer_size =&gt; 8388608 =&gt; 8388608

**Comment by sy-records** [comment]
之前有相似的issue，里面说了原因，和版本没关系，可以搜下看看。
