### ISSUE TITLE
有辦法強制不帶header嗎？

### ISSUE THREAD

**Issue by s890510** [swlib/saber#17]
請問有辦法不帶header嗎？
因為目前看起來都會自帶

**Comment by twose** [comment]
```php
SaberGM::default(['headers' => ['user-agent' => null]]);

go(function () {
    echo SaberGM::get('httpbin.org/get');
});
```

剩下的头就算你不添加 底层也会自动添加的 比如 accept-encoding 等, host头如不携带是无法访问的

**Comment by twose** [comment]
@s890510 哪些头是你不想携带的? 有些是必须的.

**Comment by s890510** [comment]
恩，有發現在coroutine-client會自動加上(有跟async-client比對過)
目前是透過一些方法去把它disable掉 (所以並沒有用saber...)
