### ISSUE TITLE
大神，怎么带着cookie去访问？

### ISSUE THREAD

**Issue by springleng** [swlib/saber#18]
[
    'before' => function (Swlib\Saber\Request $request) {
        echo "\n=====================设置Cookies====================\n";
    },
    'after' => function (Swlib\Saber\Response $response) {
        echo "\n=====================获取Cookies====================\n";
    },
]

我的想法是在以上拦截器里写，但不知如何写这块的代码。看文档说要去看Saber\Http，但没找到相关代码和文档

**Comment by twose** [comment]
options里设置cookie,
如 ['cookies' => ['foo' => 'bar']]

拦截器可以参考这个, session就是拦截器实现
https://github.com/swlib/saber/blob/f3400a653c926d524a85b4494dec7c9365b7adae/src/Saber.php#L111
