### ISSUE TITLE
文档里面对php版本要求是7.1实际上7.0也可以吧

### ISSUE THREAD

**Issue by gouchaoer** [swlib/saber#2]
我看composer里是70，源码里也没啥不兼容70的地方，这个库简直php爬虫工程师的核弹啊

**Comment by twose** [comment]
@gouchaoer 
可能因为一些问题, swoole2.x一度移除了PHP7.0支持,  现在swoole4.0是绝对稳定, 可以在任意场景使用协程(之前不能使用魔术方法等), 所以最近会抽时间更新这个lib, 发正式版.

**Comment by shuyabin** [comment]
- -为啥我的php 7.0 报错...这就有点尴尬...
![image](https://user-images.githubusercontent.com/14884581/42094079-2bdcf1b4-7be1-11e8-83f1-93aabb1220a2.png)

**Comment by twose** [comment]
@shuyabin 
看了一下, 还真是, PHP71才支持null的类型声明, 这个库全都是用最新写法的, 既然用swoole了, 最好还是持续拥抱最新版本吧

> PHP 7.1 allows for void and null return types by preceding the type declaration with a ?

那么最低版本还是得PHP71了

**Comment by gouchaoer** [comment]
依赖swoole的话，和swoole/swoft之类的保持一致从70开始是不是更好一点，因为是基础组件，那几个返回值地方感觉不用影响不大

**Comment by twose** [comment]
最近发现swoole在PHP7.0下有部分测试跑不通, 70底层还是有点问题的, 说不定会踩雷...
结合swoole的一些小bug(最近才修的), 甚至可能需要搭配swoole4.0.3才能发挥100%威力(比如连接池等)
讲道理感觉现在71占有比会高一些? 推荐还是71及以上比较省心

**Comment by xuhuaiqu** [comment]
公司版本升级到7.1 也需要不少人配合才行 虽然眼馋saber目前看来无法支持7.0啊

**Comment by twose** [comment]
7.0已被PHP官方废弃, Swoole也即将移除PHP7.0的支持
