### ISSUE TITLE
Uncaught Swlib\Http\Exception\ConnectException:Connect timeout! the server is not listening on the port or the network is missing! 

### ISSUE THREAD

**Issue by JasonBike** [swlib/saber#22]
代码是这样的:
SaberGM::psr([
                'uri' => 'https://httpbin.org/ip',
                'ssl_verify_peer' => true,
                'ssl_host_name' => 'httpbin.org',
                'proxy'=>'http://192.162.133.40:47163',
            ])->withCAFile()->getProxy();

如果加了代理会报上面的错误，去掉代理正常访问。用guzzleHttp试过代理ip正常可用

**Comment by chenhui1221** [comment]
我也出现大量的这样的异常。作者咋这么久了都不回复

**Comment by chenhui1221** [comment]
@twose  请教

**Comment by twose** [comment]
@chenhui1221 贴一下完整可运行的代码

**Comment by Mr-LP** [comment]
@twose   我也出现这样的问题了
go(function () {
    $uri = 'http://myip.ipip.net/';
    $uri = 'http://djphp.top';
    echo SaberGM::get($uri, ['proxy' => 'http://221.176.206.29:8060'])->body;
    $a=SaberGM::get($uri, ['proxy' => 'http://129.204.21.49:80']);
    // var_dump($a);
    echo $a->body;
});

**Comment by cfreew** [comment]
@twose 你好，我也出现同样的总是。
使用foreach 循环取200个以上的**不同**页面时，总是只有前几个成功，后面正常的页面也会出现这个错误。
go(function () {
    $saber = Saber::create([
        'base_uri' => '';//http://china.northnews.cn',
        'timeout'   => 10,
        'use_pool'  => true,
        'max_co'    => 2,
        'retry_time'=> 3,
        'headers' => [
            'Accept-Language' => 'en,zh-CN;q=0.9,zh;q=0.8',
            'DNT' => '1',
            'User-Agent' => null,
        ]
    ]);
    $rst = $saber->get('')->body;//'2019/0524/3094176.shtml'
});

**Comment by twose** [comment]
@cfreew 可能是频繁请求, 连接被切断,  尝试重连时被服务器端拒绝

**Comment by cfreew** [comment]
知道了，谢谢！ 频繁请求是多页面抓取不可避免的吧，我尝试下间隔请求

**Comment by twose** [comment]
@cfreew 稍微有点规模的网站都有反爬机制, 爬虫不是那么好写的
