### ISSUE TITLE
添加Client的setting自定义配置吧

### ISSUE THREAD

**Issue by amuluowin** [swlib/saber#23]
目前在用saber做clickhouse的包，由于ck的并发能力较低，适合大批量数据一次写入，默认的socket_buffer_size不够用了，或者在swoole底层可以通过co::set设置全局的配置，然后单个客户端的配置可以覆盖全局配置？

**Comment by twose** [comment]
什么版本的swoole, 最新版本buffer是无限大的, 底层会自动调度

**Comment by amuluowin** [comment]
更新到最新版本已经OK

**Comment by amuluowin** [comment]
还是有问题，swoole4.2.11版本还是存在这个问题，添加socket_buffer_size参数后就成功，没有这个参数会协程挂起到超时。

**Comment by twose** [comment]
可以使用`swoole_async_set`来调整全局的`socket_buffer_size`

**Comment by twose** [comment]
这是一个关于数据超过缓冲区大小发送失败未处理的BUG
Fixed in https://github.com/swoole/swoole-src/commit/29351d1753d46b527d2eb7d9fde6340e6105e994
