### ISSUE TITLE
大神，带get参数的websocket如何请求？

### ISSUE THREAD

**Issue by lxyzsl** [swlib/saber#28]
如果url为ws://127.0.0.1/?a=b:99999那么会报错，该如何请求
![image](https://user-images.githubusercontent.com/17881085/54743721-e14a5700-4bff-11e9-9ee7-0428ac4c9765.png)

**Comment by sy-records** [comment]
Fixed via https://github.com/swlib/saber/commit/1188d0a67d18430d5c1a11f8dcdc135852fc1e31
