### ISSUE TITLE
依赖有问题。。。

### ISSUE THREAD

**Issue by wuguobao** [swlib/saber#3]
![image](https://user-images.githubusercontent.com/3884388/42413832-65db1596-825b-11e8-9c3c-7b38dfc654c5.png)

**Comment by twose** [comment]
@wuguobao 需要在composer.json加入`"minimum-stability": "dev"`, 由于没有正式发版只能这样, 最近会发一个正式版.

**Comment by twose** [comment]
已发版本, 并且更换了更快的镜像源.
