### ISSUE TITLE
如何添加握手的参数呢?

### ISSUE THREAD

**Issue by lihaotian0607** [swlib/saber#39]
```
require_once './vendor/autoload.php';
go(function () {
    $websocket = \Swlib\SaberGM::websocket('127.0.0.1:9093'); //这里想给后面加上token和uid咋加呢?
 
});
```

**Comment by ihipop** [comment]
https://github.com/swlib/saber/issues/28
https://github.com/swlib/saber/commit/1188d0a67d18430d5c1a11f8dcdc135852fc1e31
Matser版本已经修复了 但是Master版本现在还不是正式版 有点小问题

**Comment by xinghuolei** [comment]
两个月过去了 还没合并到正式版啊

**Comment by sy-records** [comment]
Fixed via https://github.com/swlib/saber/commit/1188d0a67d18430d5c1a11f8dcdc135852fc1e31
