### ISSUE TITLE
Websocket upgrade failed by [Success].

### ISSUE THREAD

**Issue by emmeair** [swlib/saber#41]
带了get参数去升级为websocket失败, 使用js来连接是成功的

  $websocket = \Swlib\SaberGM::websocket('ws://127.0.0.1:2023/CloseOrderSercive');

            while (true) {
                echo $websocket->recv(1) . "\n";
                $websocket->push("hello");
                co::sleep(1);
            }

**Comment by ihipop** [comment]
https://github.com/swlib/saber/issues/39#issuecomment-489573138

**Comment by sy-records** [comment]
Fixed via https://github.com/swlib/saber/commit/1188d0a67d18430d5c1a11f8dcdc135852fc1e31
