### ISSUE TITLE
Swoole\Buffer is deprecated

### ISSUE THREAD

**Issue by wslinging** [swlib/saber#47]
swoole 4.4.0 版本，使用saber报错Class Swoole\Buffer is deprecated, it will be removed in v4.5.0。
file:vendor/swlib/http/src/SwooleBuffer.php line 19
请问适配4.4以上版本的saber什么时候会有呢

**Comment by wslinging** [comment]
暂时在buffstream那里的版本对比多加了一个version_compare(SWOOLE_VERSION, '4.4.0', '<')，然后走PHPMemory::class了。

**Comment by wslinging** [comment]
期待saber 2.0

**Comment by chickmy** [comment]
@twose 作者大佬什么时候修复这个问题

**Comment by twose** [comment]
v1.0.7已修复
