### ISSUE TITLE
header 使用 ContentType::MULTIPART 的时候出错

### ISSUE THREAD

**Issue by adcbguo** [swlib/saber#49]
ContentType::MULTIPART

\Swlib\Util\DataParser::toMultipartString($options['data'], $boundary);

\Swlib\Util\DataParser::__callStatic   line  80

\Swlib\Util\DataParser::arrayToMultipartString

**Comment by WuYunlong** [comment]
我也遇到这个问题
当 ContentType::MULTIPART 的时候程序报错
DataParser::arrayToMultipartString 需要两个参数但是我们仅传了一个  


另外使用这样的方式无法完成
https://pay.weixin.qq.com/wiki/doc/api/xiaowei.php?chapter=19_9 该接口的调用

**Comment by adcbguo** [comment]
> 我也遇到这个问题
> 当 ContentType::MULTIPART 的时候程序报错
> DataParser::arrayToMultipartString 需要两个参数但是我们仅传了一个
> 
> 另外使用这样的方式无法完成
> https://pay.weixin.qq.com/wiki/doc/api/xiaowei.php?chapter=19_9 该接口的调用

好像文件上传+传递POST数据一起就会出问题   
出现两个data/multipart  一个是swoole的，一个是Saber的

你现在解决了这个问题吗？

**Comment by adcbguo** [comment]
改了一些他的库代码终于解决了，太他妈操蛋了
