### ISSUE TITLE
下载一个重定向的链接文件失败

### ISSUE THREAD

**Issue by edenleung** [swlib/saber#53]
下载一个重定向的链接文件失败
```php
go(function(){
    SaberGM::download(
        'https://github.com/swlib/saber/archive/v1.0.6.tar.gz',
        './v1.0.6.tar.gz'
    );
});
```

结果
><html><body>You are being <a href="https://codeload.github.com/swlib/saber/tar.gz/v1.0.6">redirected</a>.</body></html>

**Comment by hiKitten** [comment]
go(function(){
    $save_path = './v1.0.6.tar.gz';
    $before_redirect = function (\Swlib\Saber\Request $request) use ($save_path) {
            $request->withDownloadDir($save_path);
    }; 
    SaberGM::download(
        'https://github.com/swlib/saber/archive/v1.0.6.tar.gz',
        $save_path,
        0,
        ['before_redirect' => $before_redirect]
    );
});

我这样暂时解决了，监听 before_redirect 事件，给重定向后的 request 绑定下载目录。

官方后续应该会改进这个功能吧？

**Comment by twose** [comment]
下载功能是Swoole内核提供的...一直没有支持重定向, 因为解析起来非常麻烦, 而Swoole只提供比较基础的能力...
