### ISSUE TITLE
 Uncaught Swoole\Coroutine\Http\Client\Exception: you must configure with `enable-openssl` to support ssl connection i

### ISSUE THREAD

**Issue by cys138138** [swlib/saber#58]
Uncaught Swoole\Coroutine\Http\Client\Exception: you must configure with `enable-openssl` to support ssl connection i

**Comment by cys138138** [comment]
https的都出现这个要怎么设置？

**Comment by twose** [comment]
编译Swoole的时候实验--enable-openssl编译选项
