### ISSUE TITLE
HTTP短连接连接池？

### ISSUE THREAD

**Issue by chaiyanlin** [swlib/saber#6]
请求在swoole作为网关分发请求到业务服务的场景下，如何使用saber来避免高并发场景下出现大量TIME_WAIT的现象？

连接池的方式我不是很理解，如果被请求方的webserver不支持HTTP KeepAlive的话，依然是短连接，那连接池里面的实例再每次发起新的请求时不是还要重新建立TCP吗？

**Comment by twose** [comment]
@chaiyanlin 
不支持keep-alive肯定是要重连的啊, tcp连接会在请求响应结束后就断掉的, 脱离长连接谈性能谈连接池就是耍流氓啊...建议你看看HTTP协议和TCP知识...据我所知世界上没有短连接的连接池...必须短连接还想提高性能, 相当于既要马儿跑, 又要马儿不吃草...

**Comment by chaiyanlin** [comment]
好的！感谢❤

发自我的 iPhone

在 2018年7月19日，下午6:13，twosee <notifications@github.com<mailto:notifications@github.com>> 写道：


@chaiyanlin<https://github.com/chaiyanlin>
不支持keep-alive肯定是要重连的啊, tcp连接会在请求响应结束后就断掉的, 脱离长连接谈性能谈连接池就是耍流氓啊...建议你看看HTTP协议和TCP知识...据我所知世界上没有短连接的连接池...必须短连接还想提高性能, 相当于既要马儿跑, 又要马儿不吃草...
