### ISSUE TITLE
请求 不能获取响应体的内容  好像是buffer有问题

### ISSUE THREAD

**Issue by chenjing0521** [swlib/saber#64]
```
require './vendor/autoload.php';

go(function (){
    $url = 'http://test1.xxxx.com/';
    $option = [
        'timeout' => 5,
        'retry_time' => 3,
    ];

    $ret = \Swlib\SaberGM::post($url,[],$option);

    $res1 = (clone $ret)->getBody()->getContents();

    $res2 = (string)(clone $ret);
    var_dump($res1);
    var_dump($res2);
    echo "\n";
    echo $ret;
    echo "\n";
});
```

![image](https://user-images.githubusercontent.com/43941983/63344999-4b6c5100-c384-11e9-9bbb-23296af3cd02.png)
上面的对应三个打印

第一个才是正常的操作但是 没有数据   相反  只要 带有__toString()的方法都能取到响应体

**Comment by Wiidz** [comment]
一样 我也是这个问题 拿不到body体里的内容

**Comment by twose** [comment]
向流写数据的时候指针会偏移, 但psr没有规定getContent要seek(0)...
直接转(string)是可以从头开始拿到的

**Comment by chenjing0521** [comment]
那目前这个问题是 需要自己调用是不?官方不会处理

还有个问题
https://github.com/swlib/saber/issues/49
这个问题确实有 ,请问修复了没
