### ISSUE TITLE
host filter 验证有问题?

### ISSUE THREAD

**Issue by okool** [swlib/saber#67]
目前base_uri只支持'localhost'或带点'.'的uri.

查看了源码是这样验证的.
./vendor/swlib/http/src/Uri.php
```php
  private function filterHost(string $host): string
    {
        if ($host && $host !== self::HTTP_DEFAULT_HOST && strpos($host, '.') === false) {
            throw new InvalidArgumentException("Host '{$host}' is illegal!");
        }

        return strtolower($host);
    }
```

而,我们经常需要调用本地或本域的自定义host.
```
curl http://localhost1/
curl http://user_srv/
curl http://mysql_srv/api/
curl http://redis_srv/api/
```

其它常用的http请求类,没有对host做限制,可否参考一下.
如:JS的axios,request,jquery,PHP的GuzzleHttp都没有对这个uri中的'host'做限制.

**Comment by twose** [comment]
https://github.com/swlib/http/blob/badb8053954fd188fb0e17cc7cf752e5a3c7c473/src/Uri.php#L645

之前已经去掉了, 是否为最新版?

**Comment by okool** [comment]
> https://github.com/swlib/http/blob/master/src/Uri.php#L645
> 
> 之前已经去掉了, 是否为最新版?

哦sorry ,我的问题.
composer require 默认是1.0
