### ISSUE TITLE
swlib/http 由1.0.3升级到1.0.5 request_body 为空

### ISSUE THREAD

**Issue by php-chaung** [swlib/saber#71]
swlib/http 由1.0.3升级到1.0.5 request_body 为空
php version 7.1
swlib/http 1.0.5
swlib/saber 1.0.9

存取方式不一致，导致请求体为空，请求失败

**Comment by fdreamsu** [comment]
请升级到 saber 1.0.10 已经解决该问题

**Comment by php-chaung** [comment]
ok👌
