### ISSUE TITLE
SaberGM::post 上传文件报  Socket is not connected[57]

### ISSUE THREAD

**Issue by lwmxiaobei** [swlib/saber#75]
echo SaberGM::post($this->baseUrl, $params, [
            'files' => [
                'file' => $params['file'],
           ]
        ]);

报错：WARNING	sendfile(:1324): sendfile(5, /Users/linweimin/Downloads/VCG41N670684396.jpg) failed, Error: Socket is not connected[57]

/Users/linweimin/Downloads/VCG41N670684396.jpg 这张图是存在的且有读权限

不知道为啥报这个错

**Comment by sy-records** [comment]
先关掉了，如果使用新版本还有问题请重新打开
