### ISSUE TITLE
Saber请求微信接口 无法获取值

### ISSUE THREAD

**Issue by cxjhk** [swlib/saber#78]
Saber::GM获取微信token以后 使用getBody()->getContents()获取值为空
但是单独获取getBody能获取到对象 对象里面是有返回值的

**Comment by abraaoz** [comment]
This happens because the swlib implementation of PSR-7 was incorrect. You can fix the problem by replacing the swlib Response object by guzzlehttp implementation (NOTE: you'll still be using Saber to make the requests, with all its benefits), wich is correctly implemented, so getContents() works as expected.
First, you need to install the GuzzleHttp library:
```bash
composer require guzzlehttp/guzzle
```
Then you should replace `SaberGM::get('https://api.ipify.org')` by:
```php
$request = \Swlib\Saber\Request('GET', 'https://api.ipify.org');
$brokenResponse = $request->exec()->recv();
$swlibImplementation = $brokenResponse->getBody();
$guzzleImplementation = \GuzzleHttp\Psr7\stream_for($swlibImplementation->getMetadata('hwm'));
$fixedResponse = $brokenResponse->withBody($guzzleImplementation);
echo($fixedResponse->getBody()->getContents()); // works as expected ;)
```

**Comment by fdreamsu** [comment]
getBody() 是 Request上的方法吧？你要对Swlib\SaberGM::psr()返回的对象执行recv()，再获取其中的body成员

**Comment by cxjhk** [comment]
> This happens because the swlib implementation of PSR-7 was incorrect. You can fix the problem by replacing the swlib Response object by guzzlehttp implementation (NOTE: you'll still be using Saber to make the requests, with all its benefits), wich is correctly implemented, so getContents() works as expected.
> First, you need to install the GuzzleHttp library:
> 
> ```shell
> composer require guzzlehttp/guzzle
> ```
> 
> Then you should replace `SaberGM::get('https://api.ipify.org')` by:
> 
> ```
> $request = \Swlib\Saber\Request('GET', 'https://api.ipify.org');
> $brokenResponse = $request->exec()->recv();
> $swlibImplementation = $brokenResponse->getBody();
> $guzzleImplementation = \GuzzleHttp\Psr7\stream_for($swlibImplementation->getMetadata('hwm'));
> $fixedResponse = $brokenResponse->withBody($guzzleImplementation);
> echo($fixedResponse->getBody()->getContents()); // works as expected ;)
> ```
I'm going to use the guzzle, so why don't I just guzzle it

**Comment by sy-records** [comment]
@cxjhk 用master代码可以试下有没有问题，之前可能buffer有问题
