### ISSUE TITLE
Swoole4之后已经可以在魔术方法里面使用协程

### ISSUE THREAD

**Issue by ihipop** [swlib/saber#8]
![default](https://user-images.githubusercontent.com/423077/43638051-f1e84f6a-9749-11e8-87a0-c176ec4c9203.png)

https://wiki.swoole.com/wiki/page/851.html

![default](https://user-images.githubusercontent.com/423077/43638064-f9a67204-9749-11e8-9d5f-51240f5d40d0.png)

**Comment by twose** [comment]
@ihipop 
是的, 两个文档都是我写的呢...
魔术方法虽然代码量会减少, 但其实是有一定开销的, 既然已经写好了没必要再用魔术方法了, 而且兼容性更强.
