### ISSUE TITLE
请求排查一下有的网站cookie无法获取的问题

### ISSUE THREAD

**Issue by qifengzhang007** [swlib/saber#83]
###  从同花顺网站获取cookie失败，都是空文本
```php
        $cookies=SaberGM::get('http://10jqka.com.cn/',$this->options)->cookies;   //  $this->options  主要是设置了超时时间、模拟设置的浏览器头信息等。
        var_dump($cookies->toRequestString());   //  返回空值
```

但是手动打开   http://10jqka.com.cn/  , F12-->Applications--->cookis，会发现有很多cookie

**Comment by twose** [comment]
因为它的cookie这个页面设置的, 而是其他资源加载(比如js)设置的

**Comment by qifengzhang007** [comment]
> 因为它的cookie不是这个页面设置的, 而是其他资源加载(比如js)设置的

那么请问怎么获取这种cookie ？
