### ISSUE TITLE
WEBSOKET客户端ping pong 和重连

### ISSUE THREAD

**Issue by xiongbenwu** [swlib/saber#85]
有没有大佬遇到这个问题

**Comment by zhuyong96** [comment]
重连自己代码可以实现， 客户端可以自己发送 PONG数据包 
常量WEBSOCKET_OPCODE_PONG 就是PONG数据包
$this->client->push(null, WEBSOCKET_OPCODE_PONG);

**Comment by xiongbenwu** [comment]
怎么判定当前是否断开了呢

**Comment by sy-records** [comment]
判断recv返回值，示例代码：[文档](https://wiki.swoole.com/#/coroutine_client/client?id=%e5%ae%8c%e6%95%b4%e7%a4%ba%e4%be%8b) websocket同理
