### ISSUE TITLE
Call to undefined method Swlib\Saber\Request::__cookiesInitialization() 

### ISSUE THREAD

**Issue by devilmay5** [swlib/saber#94]
![image](https://user-images.githubusercontent.com/48584022/85967037-12fdc080-b9f4-11ea-8e6f-3c5386503bb5.png)

**Comment by devilmay5** [comment]
使用master分支，实例化websocket客户端时报错

**Comment by twose** [comment]
主分支是v1.x分支, 并请用composer

**Comment by devilmay5** [comment]
使用v1.x分支的话 报错 如下
![image](https://user-images.githubusercontent.com/48584022/85969053-24959700-b9f9-11ea-952a-1ff4e8d2395f.png)
![image](https://user-images.githubusercontent.com/48584022/85969060-2bbca500-b9f9-11ea-88a3-038b44608a73.png)

**Comment by twose** [comment]
尝试升级Swoole到最新版本, 使用原生WebSocket方式连接
