### ISSUE TITLE
 Websocket upgrade failed by [Success] 这个问题解决没有

### ISSUE THREAD

**Issue by devilmay5** [swlib/saber#95]
![image](https://user-images.githubusercontent.com/48584022/85969340-ee0c4c00-b9f9-11ea-9060-c8c8ddbf509f.png)
![image](https://user-images.githubusercontent.com/48584022/85969363-febcc200-b9f9-11ea-9397-c4dd74cf411d.png)
这两种方式都尝试过了 再cli中都不行 ws地址没有问题 在web端是可以跑通的

**Comment by sy-records** [comment]
装新版的应该就可以了。Fixed via https://github.com/swlib/saber/commit/1188d0a67d18430d5c1a11f8dcdc135852fc1e31

你第二种方法就是错的。
